version: "3.8"

services:

  db:
    image: mariadb
    container_name: mariadb-server
    restart: unless-stopped
    environment:
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap123
      MYSQL_ROOT_PASSWORD: fiap123
      MYSQL_DATABASE: placeforpet
    ports:
      - "3306:3306"
    networks:
      - fiap-compose-network

networks:
  fiap-compose-network: